import {
  AcquaintancePreference,
  ActivityKind,
  AlterProfileSurveyInfoDocument,
  AlterProfileSurveyInfoMutationVariables,
  DayOfWeek,
  OrganizingOpenness,
  ParticipationGroupKind,
  SkillLevel,
  TimeOfTheDay,
} from "@/graphql/graphql-types";
import strings from "@/translations/strings";
import { QuestionKind, Survey } from "./types";

// Low → high, so each slider notch maps to the right enum value.
const acquaintanceOrder = [
  AcquaintancePreference.Nobody,
  AcquaintancePreference.One,
  AcquaintancePreference.Two,
  AcquaintancePreference.ThreePlus,
  AcquaintancePreference.Everyone,
] as const;

export const preferencesSurvey: Survey<AlterProfileSurveyInfoMutationVariables> = {
  id: "preferences",
  mutation: AlterProfileSurveyInfoDocument,
  onFinishedRoute: "/home",
  onSkippedRoute: "/home",
  successToast: strings.toast.preferencesSaved,
  questions: [
    {
      kind: QuestionKind.ActivityRating,
      title: strings.survey.preferences.activitiesTitle,
      subtitle: strings.survey.preferences.activitiesSubtitle,
      field: "preferredActivities",
      activityEnum: ActivityKind,
      activityNamespace: "enums.activityKind",
      skillEnum: SkillLevel,
      skillNamespace: "enums.skillLevel",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.sessionDurationTitle,
      field: "preferredSessionDuration",
      min: 15,
      max: 180,
      step: 15,
      unit: "min",
    },
    {
      kind: QuestionKind.SingleChoice,
      title: strings.survey.preferences.organizingTitle,
      field: "organizingOpenness",
      enum: OrganizingOpenness,
      enumNamespace: "enums.organizingOpenness",
      required: true,
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.leadershipTitle,
      field: "leadershipInclination",
      min: 1,
      max: 5,
      labelsNamespace: "survey.preferences.scaleFrequency",
    },
    {
      kind: QuestionKind.Availability,
      title: strings.survey.preferences.availabilityTitle,
      subtitle: strings.survey.preferences.availabilitySubtitle,
      field: "availabilities",
      dayEnum: DayOfWeek,
      dayNamespace: "enums.dayOfWeek",
      timeEnum: TimeOfTheDay,
      timeNamespace: "enums.timeOfTheDay",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.travelDistanceTitle,
      field: "maxTravelDistance",
      min: 1,
      max: 100,
      unit: "km",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.weeklyTargetTitle,
      field: "weeklyActivityTarget",
      min: 1,
      max: 7,
      labelsNamespace: "survey.preferences.scaleWeekly",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.discomfortTitle,
      field: "pushesThroughDiscomfort",
      min: 1,
      max: 5,
      labelsNamespace: "survey.preferences.scaleAgreement",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.groupSizeTitle,
      subtitle: strings.survey.preferences.groupSizeSubtitle,
      field: "preferredGroupSize",
      min: 1,
      max: 10,
      labelsNamespace: "survey.preferences.scaleGroupSize",
    },
    {
      kind: QuestionKind.MultiChoice,
      title: strings.survey.preferences.participationGroupsTitle,
      subtitle: strings.survey.optionalMultiSubtitle,
      field: "participationGroups",
      enum: ParticipationGroupKind,
      enumNamespace: "enums.participationGroupKind",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.acquaintanceTitle,
      field: "acquaintancePreference",
      min: 1,
      max: acquaintanceOrder.length,
      enumValues: acquaintanceOrder,
      labelsNamespace: "survey.preferences.scaleAcquaintance",
      required: true,
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.meetNewPeopleTitle,
      field: "enjoysMeetingNewPeople",
      min: 1,
      max: 5,
      labelsNamespace: "survey.preferences.scaleAgreement",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.activityVsSocialTitle,
      field: "activityVsSocial",
      min: 1,
      max: 5,
      labelsNamespace: "survey.preferences.scaleActivitySocial",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.competitionTitle,
      field: "motivatedByCompetition",
      min: 1,
      max: 5,
      labelsNamespace: "survey.preferences.scaleAgreement",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.planningHorizonTitle,
      field: "planningHorizon",
      min: 1,
      max: 5,
      labelsNamespace: "survey.preferences.scalePlanning",
    },
    {
      kind: QuestionKind.Slider,
      title: strings.survey.preferences.burdenTitle,
      field: "feelsLikeBurden",
      min: 1,
      max: 5,
      labelsNamespace: "survey.preferences.scaleAgreement",
    },
  ],
};
