import {
  AlterProfileSurveyInfoDocument,
  AlterProfileSurveyInfoMutationVariables,
  FormedRelationshipsKind,
  FrequencyOfPhycicalActivity,
  GenderNoPnts,
  MainInterest,
  MatchedParticipationLikelihood,
  PhysicalActivitySatisfaction,
  PreferredPartnerCharacteristics,
  PreferredPartySize,
  SocialInteractionImportance,
  TimeOfTheDay,
} from "@/graphql/graphql-types";
import strings from "@/translations/strings";
import { QuestionKind, Survey } from "./types";

export const preferencesSurvey: Survey<AlterProfileSurveyInfoMutationVariables> = {
  id: "preferences",
  mutation: AlterProfileSurveyInfoDocument,
  onFinishedRoute: "/home",
  questions: [
    {
      kind: QuestionKind.SingleChoice,
      title: strings.survey.preferences.mainInterestTitle,
      field: "mainInterest",
      enum: MainInterest,
      enumNamespace: "enums.mainInterest",
      required: true,
    },
    {
      kind: QuestionKind.SingleChoice,
      title: strings.survey.preferences.frequencyTitle,
      field: "frequencyOfPhysicalActivity",
      enum: FrequencyOfPhycicalActivity,
      enumNamespace: "enums.frequencyOfPhysicalActivity",
      required: true,
    },
    {
      kind: QuestionKind.SingleChoice,
      title: strings.survey.preferences.satisfactionTitle,
      field: "physicalActivitySatisfaction",
      enum: PhysicalActivitySatisfaction,
      enumNamespace: "enums.physicalActivitySatisfaction",
      required: true,
    },
    {
      kind: QuestionKind.SingleChoice,
      title: strings.survey.preferences.socialImportanceTitle,
      field: "socialInteractionImportance",
      enum: SocialInteractionImportance,
      enumNamespace: "enums.socialInteractionImportance",
      required: true,
    },
    {
      kind: QuestionKind.SingleChoice,
      title: strings.survey.preferences.partySizeTitle,
      field: "preferredPartySize",
      enum: PreferredPartySize,
      enumNamespace: "enums.preferredPartySize",
      required: true,
    },
    {
      kind: QuestionKind.MultiChoice,
      title: strings.survey.preferences.relationshipsTitle,
      subtitle: strings.survey.optionalMultiSubtitle,
      field: "formedRelationshipKinds",
      enum: FormedRelationshipsKind,
      enumNamespace: "enums.formedRelationshipsKind",
    },
    {
      kind: QuestionKind.MultiChoice,
      title: strings.survey.preferences.partnerCharsTitle,
      subtitle: strings.survey.optionalMultiSubtitle,
      field: "preferredPartnerCharacteristics",
      enum: PreferredPartnerCharacteristics,
      enumNamespace: "enums.preferredPartnerCharacteristics",
    },
    {
      kind: QuestionKind.SingleChoice,
      title: strings.survey.preferences.matchedLikelihoodTitle,
      field: "matchedParticipationLikelihood",
      enum: MatchedParticipationLikelihood,
      enumNamespace: "enums.matchedParticipationLikelihood",
      required: true,
    },
    {
      kind: QuestionKind.MultiChoice,
      title: strings.survey.preferences.genderPrefTitle,
      subtitle: strings.survey.optionalMultiSubtitle,
      field: "genderPreference",
      enum: GenderNoPnts,
      enumNamespace: "enums.genderNoPnts",
    },
    {
      kind: QuestionKind.MultiChoice,
      title: strings.survey.preferences.timeOfDayTitle,
      subtitle: strings.survey.optionalMultiSubtitle,
      field: "preferredTimeOfTheDay",
      enum: TimeOfTheDay,
      enumNamespace: "enums.timeOfTheDay",
    },
  ],
};
